### ISSUE TITLE
Clients aren't using defined DNS (Raspbian)

### ISSUE THREAD

**Issue by genox** [subspacecommunity/subspace#164]
Hi,

I installed WireGuard and Subspace on a RPi using docker/docker-compose and defined a pi-hole DNS server in the docker-compose file:

```
    subspace:
        image: subspacecommunity/subspace:latest
        container_name: subspace
        volumes:
            - /opt/docker/subspace:/data
        restart: always
        environment:
            - SUBSPACE_HTTP_HOST=xxxxxxxxxxxxxxx
            - SUBSPACE_LETSENCRYPT=false
            - SUBSPACE_HTTP_INSECURE=true
            - SUBSPACE_HTTP_ADDR=":80"
            - SUBSPACE_NAMESERVERS=192.168.1.3
            - SUBSPACE_LISTENPORT=51900
            - SUBSPACE_IPV6_NAT_ENABLED=1
        cap_add:
            - NET_ADMIN
        network_mode: "host"
```

Clients connect fine but DNS requests aren't handled by 192.168.1.3 - however, I can access the local IP just fine from connected devices, e.g. loading the pi-hole admin UI.

The RPi itself resolves using the correct DNS itself (defined via DHCP):

```
; <<>> DiG 9.11.5-P4-5.1+deb10u3-Raspbian <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13095
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		50	IN	A	172.217.168.14

;; Query time: 60 msec
;; SERVER: 192.168.1.3#53(192.168.1.3)
;; WHEN: Sun Apr 25 20:27:46 BST 2021
;; MSG SIZE  rcvd: 55
```

I made sure I followed the setup directions while installing Subspace.

Not sure if it has anything to do with the hardcoded 1.1.1.1 in the container's /etc/resolv.conf:

```
/etc # cat /etc/resolv.conf
nameserver 1.1.1.1

/etc # nslookup google.com
Server:		1.1.1.1
Address:	1.1.1.1:53

Non-authoritative answer:
Name:	google.com
Address: 172.217.168.46

Non-authoritative answer:
Name:	google.com
Address: 2a00:1450:400a:802::200e
```

I'd greatly appreciate any advice. Thanks!
