### ISSUE TITLE
The container keeps restarting

### ISSUE THREAD

**Issue by ramoncio** [subspacecommunity/subspace#225]
Thanks for your nice work, but I can't make it work in my CoreElec (aarch64) box.

I used this composer file in Portainer:

```
version: "3.3"
services:
  subspace:
   image: subspacecommunity/subspace:latest
   container_name: subspace
   volumes:
    - /storage/dockers/subspace:/data
   ports:
    - 4545:80
   restart: always
   environment:
    - SUBSPACE_HTTP_HOST=subspace.mydomain.duckdns.org
    - SUBSPACE_HTTP_INSECURE=true
    - SUBSPACE_HTTP_ADDR=":80"
    - SUBSPACE_NAMESERVERS=1.1.1.1,8.8.8.8
    - SUBSPACE_LISTENPORT=51820
    - SUBSPACE_IPV6_NAT_ENABLED=0
    - SUBSPACE_DISABLE_DNS=1
   cap_add:
    - NET_ADMIN
   network_mode: "host"
```

But the container keeps restarting with this error repeating in the logs:

```
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.3 (legacy): unknown option "--to"
Try `ip6tables -h' or 'ip6tables --help' for more information.
```
```
 # ip6tables --version
ip6tables v1.4.21
```

I disabled ipv6 in my host with sysctl net.ipv6.conf.default.disable_ipv6=1 probably that's related?
Can't I just disable ipv6 in subspace?
