### ISSUE TITLE
Proposal for docker-compose and systemd-resolved disable

### ISSUE THREAD

**Issue by Coffeeri** [subspacecommunity/subspace#47]
Firstly, thanks for your work it seems to work really great and lowers the inhibition to use wireguard!

I installed subspace via the given docker-compose file and noticed, that the quotes around IPs need to be removed:
```yml
version: "3.3"
services:
  subspace:
   image: subspacecommunity/subspace:latest
   container_name: subspace
   volumes:
    - /usr/bin/wg:/usr/bin/wg
    - /opt/docker/subspace:/data
   restart: always
   environment:
    - SUBSPACE_HTTP_HOST=subspace.example.org
    - SUBSPACE_LETSENCRYPT=true
    - SUBSPACE_HTTP_INSECURE=false
    - SUBSPACE_HTTP_ADDR=":80"
    - SUBSPACE_NAMESERVER=1.1.1.1
    - SUBSPACE_LISTENPORT=51820
    - SUBSPACE_IPV4_POOL=10.99.97.0/24
    - SUBSPACE_IPV6_POOL=fd00::10:97:0/64 # remove quotes
    - SUBSPACE_IPV4_GW=10.99.97.1 # remove quotes
    - SUBSPACE_IPV6_GW=fd00::10:97:1 # remove quotes
    - SUBSPACE_IPV6_NAT_ENABLED=1
   cap_add:
    - NET_ADMIN
   network_mode: "host"
``` 

**Secondly**, for people who run into the problem where the logs say
> dnsmasq: failed to create listening socket for port 53: Address already in use_ 

... you might need to disable **systemd-resolved**:
`sudo systemctl disable systemd-resolved`
`sudo systemctl stop systemd-resolved`

**In the end** it might be useful to add: 
_/etc/modules-load.d/wireguard.conf
/etc/modules-load.d/iptable_nat.conf
/etc/modules-load.d/ip6table_nat.conf_
such that the modules will be loaded when rebooting.
