### ISSUE TITLE
Successful login does not continue past /signin

### ISSUE THREAD

**Issue by wanaoishi** [subspacecommunity/subspace#85]
**Describe the bug**
Successful auth just goes back to the "Admin Sign In"

I currently use Docker-compose to run the server and here are the details of the docker-compose:
```
version: "3.7"
services:
  subspace:
    image: subspacecloud/subspace:latest
    container_name: subspace
    volumes:
      - /usr/bin/wg:/usr/bin/wg
      - /srv/app/wireguard:/data
    restart: always
    expose:
      - 8080
    ports:
      - "553:53"
    environment:
      - SUBSPACE_HTTP_HOST=space.xxx
      - SUBSPACE_LETSENCRYPT=false
      - SUBSPACE_HTTP_INSECURE=false
      - SUBSPACE_HTTP_ADDR=":8080"
      - SUBSPACE_NAMESERVER=1.1.1.1
      - SUBSPACE_LISTENPORT=51820
      - SUBSPACE_IPV4_POOL=10.99.97.0/24
      - SUBSPACE_IPV6_POOL=fd00::10:97:0/64
      - SUBSPACE_IPV4_GW=10.99.97.1
      - SUBSPACE_IPV6_GW=fd00::10:97:1
      - SUBSPACE_IPV6_NAT_ENABLED=1
      - VIRTUAL_HOST=vpn.xxx
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=vpn.xxx
      - LETSENCRYPT_EMAIL=it@xxx
    cap_add:
      - NET_ADMIN
    network_mode: "host"
```
