### ISSUE TITLE
Cannot start docker container. Exits with `iptables: No chain/target/match by that name.`

### ISSUE THREAD

**Issue by jerrac** [subspacecommunity/subspace#93]
**Describe the bug**
I cannot start the docker container. It exits with `RTNETLINK answers: Not supported` message.

**To Reproduce**
1. Set up Ubuntu 18.04 vm.
2. Follow the install instructions in the README.md. (Adding wireguard ppa, removing dnsmasq, etc.)
3. Create a docker-compose file like this:
```yaml
version: "3.3"
services:
  subspace:
    image: subspacecommunity/subspace:latest
    container_name: subspace
    volumes:
      - /usr/bin/wg:/usr/bin/wg
      - /srv/subspace/data:/data
    restart: always
    environment:
      - SUBSPACE_HTTP_HOST=vpn.dynamicdns.hostname
      - SUBSPACE_LETSENCRYPT=false
      - SUBSPACE_HTTP_INSECURE=true
      - SUBSPACE_HTTP_ADDR=":80"
      - SUBSPACE_NAMESERVER=192.168.1.1
      - SUBSPACE_LISTENPORT=51820
      - SUBSPACE_IPV4_POOL=10.99.97.0/24
      - SUBSPACE_IPV6_POOL=fd00::10:97:0/64
      - SUBSPACE_IPV4_GW=10.99.97.1
      - SUBSPACE_IPV6_GW=fd00::10:97:1
      - SUBSPACE_IPV6_NAT_ENABLED=0
    cap_add:
      - NET_ADMIN
    network_mode: "host"
```
4. Run `docker-compose up --force-recreate`.

**Expected behavior**
A functional subspace container should start.

**Actual behavior**
```
root@vpn:/srv/subspace# docker-compose up --force-recreate
Recreating subspace ... done
Attaching to subspace
subspace    | + '[' -z vpn.dynamicdns.hostname ]
subspace    | + '[' -z  ]
subspace    | + export 'SUBSPACE_BACKLINK='
subspace    | + '[' -z 10.99.97.0/24 ]
subspace    | + '[' -z fd00::10:97:0/64 ]
subspace    | + '[' -z 192.168.1.1 ]
subspace    | + '[' -z false ]
subspace    | + '[' -z '":80"' ]
subspace    | + '[' -z 51820 ]
subspace    | + '[' -z true ]
subspace    | + export 'DEBIAN_FRONTEND=noninteractive'
subspace    | + '[' -z 10.99.97.1 ]
subspace    | + '[' -z fd00::10:97:1 ]
subspace    | + '[' -z 0 ]
subspace    | + echo 'nameserver 192.168.1.1'
subspace    | + '[' -z  ]
subspace    | + /sbin/iptables -t nat --check POSTROUTING -s 10.99.97.0/24 -j MASQUERADE
subspace    | + /sbin/iptables --check FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
subspace    | + /sbin/iptables --check FORWARD -s 10.99.97.0/24 -j ACCEPT
subspace    | + '[[' 0 -gt 0 ]]
subspace    | + /sbin/iptables -t nat --check OUTPUT -s 10.99.97.0/24 -p udp --dport 53 -j DNAT --to 10.99.97.1:53
subspace    | + /sbin/iptables -t nat --check OUTPUT -s 10.99.97.0/24 -p tcp --dport 53 -j DNAT --to 10.99.97.1:53
subspace    | + /sbin/ip6tables --wait -t nat --check OUTPUT -s fd00::10:97:0/64 -p udp --dport 53 -j DNAT --to fd00::10:97:1
subspace    | + /sbin/ip6tables --wait -t nat --check OUTPUT -s fd00::10:97:0/64 -p tcp --dport 53 -j DNAT --to fd00::10:97:1
subspace    | + test -d /data/wireguard
subspace    | + cat
subspace    | + cat /data/wireguard/server.private
subspace    | + cat /data/wireguard/peers/null.conf
subspace    | + ip link show wg0
subspace    | + ip link add wg0 type wireguard
subspace    | RTNETLINK answers: Not supported

```
**Additional context**
Server OS: Ubuntu 18.04
```
root@vpn:/srv/subspace# docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
subspacecommunity/subspace   latest              8825e8dfbe8f        2 days ago          38.4MB
```

I set `SUBSPACE_IPV6_NAT_ENABLED=0` because I am not using IPV6 in my internal network.

I tried just commenting out the IPV6 environment variables, but then the iptable rules didn't apply, and it errored out due to that.

I have DD-WRT on my router between my network and the WAN. My dynamic dns address resolves to my isp provided dhcp address outside my network. Inside I've set it to the Ubuntu VM I'm using to host subspace. But I have had odd issues where my desktop resovles the dns address to my WAN ip.... That said, the Ubuntu vm does resolve the dynamic dns address of itself, to it's internal ip. 

Oh, and DD-WRT is set to forward ports 80 and 443 to the internal ip of the Ubuntu VM.

Any ideas what my issue is?
